from . import offer
from . import product_product
from . import project
from . import default_domain
from . import project_task
from  . import res_config_settings
from . import res_company
from . import business_localisation
from . import sale
from . import business_unit
from . import sale_order_template
from . import sale_order_line