# -*- coding: utf-8 -*-
{
    'name': 'cap_requirements',
    'description': "  ",
    "author": "Konsultoo Software Consulting PVT. LTD.",
    "website": "https://www.konsultoo.com/",
    "category": "Extra Tools",
    "version": "19.0.0.1",
    'depends': ['cap_domain', 'planning', 'sale_timesheet'],
    'data': [
        "security/ir.model.access.csv",
        "security/project_requirement_security_view.xml",
        "security/project_domain_history_security.xml",
        "wizard/project_requirement_wizard_view.xml",
        "wizard/project_planning_wizard_views.xml",
        "views/template_requirement_view.xml",
        "views/project_requirement_view.xml",
        "views/project_view.xml",
        "views/project_task_view.xml",
        "views/meta_template_requirement_view.xml",
        "views/project_domain_view.xml",
        "views/project_domain_history_view.xml",
        "views/export_requirement_server_action.xml",
        "views/project_task_type_inherit_views.xml",
	"views/meta_project_requirement_views.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
