from . import product_category_ksc
from . import product_ksc
from . import product_uom_category_ksc
from . import product_uom_ksc
from . import res_partner_ksc
from . import sale_order_ksc
from . import sale_order_line_ksc
from . import res_country_ksc
from . import res_state_ksc
from . import crm_team_ksc
from . import crm_lead_ksc
from . import crm_lead_line_ksc
from . import stock_warehouse_ksc
from . import stock_location_ksc
