# -*- coding: utf-8 -*-
{
    'name': 'Project Test',
    "version": "19.0.0.1",
    'description': "This module is used for Testing Purpose of Projects",
    'website': 'https://www.konsultoo.com/app/cap_project_test',
    'depends': ['cap_requirements', 'cap_project_feedback', 'cap_quality_issue_log'],
    "author": "Konsultoo Software Consulting PVT. LTD.",
    "category": "Extra Tools",
    "summary": "",
    'data': [
        "security/ir.model.access.csv",
        "security/test_security_view.xml",
        "data/mail_template_for_session_test.xml",
        "data/quality_category_data.xml",
        "data/quality_issue_type_data_file.xml",
        "views/template_test_view.xml",
        "views/test_view.xml",
        "views/session_test_view.xml",
        "views/execution_test_view.xml",
        "views/template_requirement_view.xml",
        "views/project_requirement_view.xml",
        "views/project_view.xml",
        "views/phase_view.xml",
        "views/project_domain_view.xml",
        "views/project_task_view.xml",
        "views/task_validation_status_view.xml",
        "views/quality_issue_log_views.xml"
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
